// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/lifeforge/AiCoach.tsx": () => import("../components/mockups/lifeforge/AiCoach.tsx"),
  "./components/mockups/lifeforge/AiLoading.tsx": () => import("../components/mockups/lifeforge/AiLoading.tsx"),
  "./components/mockups/lifeforge/AiPlan.tsx": () => import("../components/mockups/lifeforge/AiPlan.tsx"),
  "./components/mockups/lifeforge/Analytics.tsx": () => import("../components/mockups/lifeforge/Analytics.tsx"),
  "./components/mockups/lifeforge/Auth.tsx": () => import("../components/mockups/lifeforge/Auth.tsx"),
  "./components/mockups/lifeforge/Dashboard.tsx": () => import("../components/mockups/lifeforge/Dashboard.tsx"),
  "./components/mockups/lifeforge/Diet.tsx": () => import("../components/mockups/lifeforge/Diet.tsx"),
  "./components/mockups/lifeforge/Gamification.tsx": () => import("../components/mockups/lifeforge/Gamification.tsx"),
  "./components/mockups/lifeforge/GoalSelect.tsx": () => import("../components/mockups/lifeforge/GoalSelect.tsx"),
  "./components/mockups/lifeforge/HabitCreate.tsx": () => import("../components/mockups/lifeforge/HabitCreate.tsx"),
  "./components/mockups/lifeforge/Habits.tsx": () => import("../components/mockups/lifeforge/Habits.tsx"),
  "./components/mockups/lifeforge/Learning.tsx": () => import("../components/mockups/lifeforge/Learning.tsx"),
  "./components/mockups/lifeforge/LifeForgeApp.tsx": () => import("../components/mockups/lifeforge/LifeForgeApp.tsx"),
  "./components/mockups/lifeforge/Lifestyle.tsx": () => import("../components/mockups/lifeforge/Lifestyle.tsx"),
  "./components/mockups/lifeforge/Onboarding.tsx": () => import("../components/mockups/lifeforge/Onboarding.tsx"),
  "./components/mockups/lifeforge/Premium.tsx": () => import("../components/mockups/lifeforge/Premium.tsx"),
  "./components/mockups/lifeforge/Problem.tsx": () => import("../components/mockups/lifeforge/Problem.tsx"),
  "./components/mockups/lifeforge/Routine.tsx": () => import("../components/mockups/lifeforge/Routine.tsx"),
  "./components/mockups/lifeforge/Settings.tsx": () => import("../components/mockups/lifeforge/Settings.tsx"),
  "./components/mockups/lifeforge/Social.tsx": () => import("../components/mockups/lifeforge/Social.tsx"),
  "./components/mockups/lifeforge/Splash.tsx": () => import("../components/mockups/lifeforge/Splash.tsx")
};
